# This is a sample policy to demonstrate configuring  RBAC for managed clusters using admin and view-only roles
# This Policy considers that below groups needs to be pre-existing before the policy can be configured.
#   Groups:  acm-admins, ac-viewonly-users
#   Group acm-admins to have admin access to all managed clusters
#   Group ac-viewonly-users to have view-only access to all managed clusters
# ManagedclusterX refers to the name of any managed cluster
# This Policy Configures the following rbac model for the above scenario
#   UsersGroups:  acm-admins, ac-viewonly-users
#   Rolebindings:
#     acm-admins group has cluster-admin access to all managed clusters including the hub cluster
#     ac-viewonly-users group has view-only access to all managed clusters including the hub cluster

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configure-clusterlevel-rbac
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configure-clusterlevel-rbac-example
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: mc-view-managed-cluster
                  subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: ac-viewonly-users
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: open-cluster-management:view:managed-cluster
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: ns-view-managed-cluster
                  namespace: managed-cluster
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: ac-viewonly-users
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: mc-admin-managed-cluster
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: acm-admins
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: open-cluster-management:admin:managed-cluster
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: ns-admin-managed-cluster
                  namespace: managed-cluster
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: acm-admins
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin   
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-configure-clusterlevel-rbac
  namespace: policies
placementRef:
  name: placement-policy-configure-clusterlevel-rbac
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-configure-clusterlevel-rbac
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-configure-clusterlevel-rbac
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: local-cluster, operator: In, values: ['true']}
